-- Book Worm schema (spec 0002). Must run on PostgreSQL 16 and on H2 in PostgreSQL mode:
-- varchar only (no text/char), "timestamp with time zone" written in full, named constraints,
-- no partial, functional or regex based rules (those live in Bean Validation and the services).

CREATE TABLE users (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY,
    email               varchar(255) NOT NULL,
    password_hash       varchar(100) NOT NULL,
    first_name          varchar(100) NOT NULL,
    last_name           varchar(100) NOT NULL,
    phone               varchar(20),
    role                varchar(20)  NOT NULL,
    gift_points_balance int          NOT NULL,
    created_at          timestamp with time zone NOT NULL,
    updated_at          timestamp with time zone NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT ck_users_email_lower CHECK (email = lower(email)),
    CONSTRAINT ck_users_role CHECK (role IN ('CUSTOMER', 'ADMIN')),
    CONSTRAINT ck_users_points CHECK (gift_points_balance >= 0)
);

CREATE TABLE addresses (
    id             bigint GENERATED BY DEFAULT AS IDENTITY,
    user_id        bigint       NOT NULL,
    first_name     varchar(100) NOT NULL,
    last_name      varchar(100) NOT NULL,
    email          varchar(255) NOT NULL,
    phone          varchar(20)  NOT NULL,
    street_address varchar(255) NOT NULL,
    barangay       varchar(100),
    city           varchar(100) NOT NULL,
    province       varchar(100) NOT NULL,
    zip_code       varchar(4)   NOT NULL,
    country        varchar(60)  NOT NULL,
    is_default     boolean      NOT NULL,
    created_at     timestamp with time zone NOT NULL,
    CONSTRAINT pk_addresses PRIMARY KEY (id),
    CONSTRAINT fk_addresses_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT ck_addresses_zip CHECK (char_length(zip_code) = 4)
);

CREATE TABLE categories (
    id   bigint GENERATED BY DEFAULT AS IDENTITY,
    name varchar(60) NOT NULL,
    slug varchar(60) NOT NULL,
    CONSTRAINT pk_categories PRIMARY KEY (id),
    CONSTRAINT uq_categories_name UNIQUE (name),
    CONSTRAINT uq_categories_slug UNIQUE (slug)
);

CREATE TABLE genres (
    id   bigint GENERATED BY DEFAULT AS IDENTITY,
    name varchar(60) NOT NULL,
    CONSTRAINT pk_genres PRIMARY KEY (id),
    CONSTRAINT uq_genres_name UNIQUE (name)
);

CREATE TABLE authors (
    id        bigint GENERATED BY DEFAULT AS IDENTITY,
    name      varchar(150) NOT NULL,
    photo_url varchar(500),
    bio       varchar(2000),
    CONSTRAINT pk_authors PRIMARY KEY (id),
    CONSTRAINT uq_authors_name UNIQUE (name)
);

CREATE TABLE publishers (
    id          bigint GENERATED BY DEFAULT AS IDENTITY,
    name        varchar(150) NOT NULL,
    description varchar(2000),
    CONSTRAINT pk_publishers PRIMARY KEY (id),
    CONSTRAINT uq_publishers_name UNIQUE (name)
);

CREATE TABLE books (
    id              bigint GENERATED BY DEFAULT AS IDENTITY,
    title           varchar(255)   NOT NULL,
    description     varchar(2000)  NOT NULL,
    format          varchar(20)    NOT NULL,
    language        varchar(40)    NOT NULL,
    price           numeric(12, 2) NOT NULL,
    front_cover_url varchar(500),
    back_cover_url  varchar(500),
    stock_quantity  int            NOT NULL,
    copies_sold     int            NOT NULL,
    publish_date    date           NOT NULL,
    category_id     bigint         NOT NULL,
    author_id       bigint         NOT NULL,
    publisher_id    bigint         NOT NULL,
    created_at      timestamp with time zone NOT NULL,
    updated_at      timestamp with time zone NOT NULL,
    CONSTRAINT pk_books PRIMARY KEY (id),
    CONSTRAINT fk_books_category FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT fk_books_author FOREIGN KEY (author_id) REFERENCES authors (id),
    CONSTRAINT fk_books_publisher FOREIGN KEY (publisher_id) REFERENCES publishers (id),
    CONSTRAINT uq_books_title_format UNIQUE (title, format),
    CONSTRAINT ck_books_format CHECK (format IN ('PAPERBACK', 'HARDCOVER', 'EBOOK')),
    CONSTRAINT ck_books_price CHECK (price >= 0),
    CONSTRAINT ck_books_stock CHECK (stock_quantity >= 0),
    CONSTRAINT ck_books_sold CHECK (copies_sold >= 0)
);

CREATE TABLE book_genres (
    book_id  bigint NOT NULL,
    genre_id bigint NOT NULL,
    CONSTRAINT pk_book_genres PRIMARY KEY (book_id, genre_id),
    CONSTRAINT fk_book_genres_book FOREIGN KEY (book_id) REFERENCES books (id) ON DELETE CASCADE,
    CONSTRAINT fk_book_genres_genre FOREIGN KEY (genre_id) REFERENCES genres (id)
);

CREATE TABLE cart_items (
    id         bigint GENERATED BY DEFAULT AS IDENTITY,
    user_id    bigint NOT NULL,
    book_id    bigint NOT NULL,
    quantity   int    NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_cart_items PRIMARY KEY (id),
    CONSTRAINT fk_cart_items_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_cart_items_book FOREIGN KEY (book_id) REFERENCES books (id),
    CONSTRAINT uq_cart_items_user_book UNIQUE (user_id, book_id),
    CONSTRAINT ck_cart_items_qty CHECK (quantity > 0)
);

CREATE TABLE orders (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY,
    order_number            varchar(30)    NOT NULL,
    user_id                 bigint         NOT NULL,
    status                  varchar(20)    NOT NULL,
    ship_first_name         varchar(100)   NOT NULL,
    ship_last_name          varchar(100)   NOT NULL,
    ship_email              varchar(255)   NOT NULL,
    ship_phone              varchar(20)    NOT NULL,
    ship_street_address     varchar(255)   NOT NULL,
    ship_barangay           varchar(100),
    ship_city               varchar(100)   NOT NULL,
    ship_province           varchar(100)   NOT NULL,
    ship_zip_code           varchar(4)     NOT NULL,
    ship_country            varchar(60)    NOT NULL,
    subtotal                numeric(12, 2) NOT NULL,
    vat_rate                numeric(5, 4)  NOT NULL,
    vat_amount              numeric(12, 2) NOT NULL,
    delivery_charge         numeric(12, 2) NOT NULL,
    gift_points_redeemed    int            NOT NULL,
    gift_points_amount      numeric(12, 2) NOT NULL,
    total_amount            numeric(12, 2) NOT NULL,
    gift_points_earned      int            NOT NULL,
    estimated_delivery_date date           NOT NULL,
    placed_at               timestamp with time zone NOT NULL,
    paid_at                 timestamp with time zone,
    shipped_at              timestamp with time zone,
    delivered_at            timestamp with time zone,
    cancelled_at            timestamp with time zone,
    updated_at              timestamp with time zone NOT NULL,
    CONSTRAINT pk_orders PRIMARY KEY (id),
    CONSTRAINT uq_orders_number UNIQUE (order_number),
    CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT ck_orders_status CHECK (status IN ('PENDING_PAYMENT', 'CONFIRMED', 'SHIPPED', 'DELIVERED', 'CANCELLED')),
    CONSTRAINT ck_orders_amounts CHECK (
        subtotal >= 0 AND vat_rate >= 0 AND vat_amount >= 0 AND delivery_charge >= 0
        AND gift_points_redeemed >= 0 AND gift_points_amount >= 0
        AND total_amount >= 0 AND gift_points_earned >= 0),
    CONSTRAINT ck_orders_total CHECK (total_amount = subtotal + vat_amount + delivery_charge - gift_points_amount)
);

CREATE TABLE order_items (
    id         bigint GENERATED BY DEFAULT AS IDENTITY,
    order_id   bigint         NOT NULL,
    book_id    bigint         NOT NULL,
    title      varchar(255)   NOT NULL,
    format     varchar(20)    NOT NULL,
    unit_price numeric(12, 2) NOT NULL,
    quantity   int            NOT NULL,
    line_total numeric(12, 2) NOT NULL,
    CONSTRAINT pk_order_items PRIMARY KEY (id),
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT fk_order_items_book FOREIGN KEY (book_id) REFERENCES books (id),
    CONSTRAINT ck_order_items_format CHECK (format IN ('PAPERBACK', 'HARDCOVER', 'EBOOK')),
    CONSTRAINT ck_order_items_qty CHECK (quantity > 0),
    CONSTRAINT ck_order_items_price CHECK (unit_price >= 0),
    CONSTRAINT ck_order_items_line CHECK (line_total = unit_price * quantity)
);

CREATE TABLE payments (
    id             bigint GENERATED BY DEFAULT AS IDENTITY,
    order_id       bigint         NOT NULL,
    method         varchar(20)    NOT NULL,
    amount         numeric(12, 2) NOT NULL,
    status         varchar(20)    NOT NULL,
    card_last4     varchar(4),
    transaction_id varchar(50)    NOT NULL,
    failure_reason varchar(120),
    created_at     timestamp with time zone NOT NULL,
    refunded_at    timestamp with time zone,
    CONSTRAINT pk_payments PRIMARY KEY (id),
    CONSTRAINT uq_payments_txn UNIQUE (transaction_id),
    CONSTRAINT fk_payments_order FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT ck_payments_method CHECK (method IN ('CREDIT_CARD', 'DEBIT_CARD', 'E_WALLET')),
    CONSTRAINT ck_payments_status CHECK (status IN ('SUCCESS', 'FAILED', 'REFUNDED')),
    CONSTRAINT ck_payments_amount CHECK (amount >= 0),
    CONSTRAINT ck_payments_last4 CHECK (card_last4 IS NULL OR char_length(card_last4) = 4),
    CONSTRAINT ck_payments_card CHECK (method = 'E_WALLET' OR card_last4 IS NOT NULL)
);

CREATE TABLE gift_point_transactions (
    id         bigint GENERATED BY DEFAULT AS IDENTITY,
    user_id    bigint      NOT NULL,
    order_id   bigint      NOT NULL,
    type       varchar(20) NOT NULL,
    points     int         NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_gift_point_transactions PRIMARY KEY (id),
    CONSTRAINT fk_gpt_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_gpt_order FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT ck_gpt_type CHECK (type IN ('EARNED', 'REDEEMED', 'RESTORED', 'REVERSED')),
    CONSTRAINT ck_gpt_sign CHECK (
        (type IN ('EARNED', 'RESTORED') AND points > 0)
        OR (type IN ('REDEEMED', 'REVERSED') AND points < 0))
);

-- Global order counter for BW-yyyyMMdd-NNNNNN numbers; a rolled back insert leaves a gap, which is fine.
CREATE SEQUENCE order_number_seq;

CREATE INDEX ix_books_category ON books (category_id);
CREATE INDEX ix_books_author ON books (author_id);
CREATE INDEX ix_books_publisher ON books (publisher_id);
CREATE INDEX ix_books_publish_date ON books (publish_date);
CREATE INDEX ix_book_genres_genre ON book_genres (genre_id);
CREATE INDEX ix_addresses_user ON addresses (user_id);
CREATE INDEX ix_orders_user_placed ON orders (user_id, placed_at);
CREATE INDEX ix_order_items_order ON order_items (order_id);
CREATE INDEX ix_order_items_book ON order_items (book_id);
CREATE INDEX ix_payments_order ON payments (order_id);
CREATE INDEX ix_gpt_user_created ON gift_point_transactions (user_id, created_at);
